pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

include ':core', ':asm', ':sim',
        ':unicode:v6_0', ':unicode:v17_0',
        ':tests:unit',
        ':tests:parity:re2j',
        ':tests:parity:re2j-suite',
        ':tests:parity:rebar',
        ':benchmarks:micro',
        ':testlib:rebar', ':testlib:parity'
