package io.github.jemmix.tdfa;

import io.github.jemmix.tdfa.tdfa.TdfaRunner;
import io.github.jemmix.tdfa.tnfa.Tnfa;
import io.github.jemmix.tdfa.vm.MatchResult;

/**
 * Public entry point. Compile once, match many.
 *
 *   Regex r = Regex.compile("(\\w+)@(\\w+)");
 *   if (r.find("hello world user@example.com")) {
 *       MatchResult m = r.find(input, 0);
 *   }
 *
 * Engine: Borsotti-Trofimovich 2022 TDFA(1) compiled AOT (paper Algorithm 3).
 */
public final class Regex {
    private final Engine engine;
    private final int groupCount;

    public interface Engine {
        boolean matches(CharSequence input);
        boolean find(CharSequence input);
        MatchResult match(CharSequence input, int from);
    }

    public static Regex compile(String pattern) {
        return compile(pattern, false);
    }

    /** @param bytecode if true, lower to a specialized hidden class via ASM. */
    public static Regex compile(String pattern, boolean bytecode) {
        Tnfa nfa = Tnfa.compile(pattern);
        io.github.jemmix.tdfa.tdfa.Tdfa tdfa = io.github.jemmix.tdfa.tdfa.Tdfa.compile(nfa);
        Engine engine = bytecode
                ? io.github.jemmix.tdfa.asm.TdfaAsmBackend.compile(tdfa)
                : new io.github.jemmix.tdfa.tdfa.TdfaRunner(nfa);
        return new Regex(engine, nfa.groupCount);
    }

    /** Engine backed by the interpreted VM (slower, no ASM dependency). */
    public static Regex compileVm(String pattern) { return compile(pattern, false); }

    /** Engine backed by ASM-generated bytecode (fast; requires the {@code tdfa-jvm-asm} path). */
    public static Regex compileAsm(String pattern) { return compile(pattern, true); }

    private Regex(Engine engine, int groupCount) {
        this.engine = engine; this.groupCount = groupCount;
    }

    public boolean matches(CharSequence input) { return engine.matches(input); }
    public boolean find(CharSequence input) { return engine.find(input); }
    public MatchResult find(CharSequence input, int from) { return engine.match(input, from); }

    public int groupCount() { return groupCount; }
}
