package io.github.jemmix.tdfa.core;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a member that generated bytecode links <em>by name</em>. The ASM
 * backends ({@code TdfaAsmBackend}, {@code ShellEmitter}) resolve these
 * members through string constants, not Java references: renaming one,
 * changing its signature, or dropping it does not fail any compile-time
 * build — it surfaces as {@code NoSuchMethodError}/{@code NoSuchFieldError}
 * (or {@code IllegalAccessError}) at pattern-compile or match time, in
 * production.
 *
 * <p>Roughly 30 members across {@code TdfaRunner}, {@code MatchHolder},
 * {@code RegPool}, {@code MatchResult}, {@code core.Matcher},
 * {@code TDFAPattern}, {@code PatternMatcher} and {@code Pattern.Utf8}
 * carry this marker. If a marked member must change, the emitters'
 * descriptor constants must change in the same commit, and the parity
 * suites (which load generated classes end-to-end) must run.
 *
 * <p>This annotation is documentation for maintainers and tools; it has no
 * runtime behavior. RUNTIME retention lets EmittedSurfaceConformanceTest
 * enforce that every emitted-code hook stays marked (and present) — turning
 * a would-be production NoSuchMethodError into a test failure.
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.FIELD})
public @interface EmittedSurface {
}
