package io.github.jemmix.tdfa.tdfa;

import io.github.jemmix.tdfa.core.EmittedSurface;

/**
 * Per-thread register-array pool for the ASM-generated tier.
 *
 * <p>The generated walk leaf ({@code extractOne}) fires once per candidate
 * start in scan ladders; allocating a fresh {@code int[]} per probe was the
 * top allocation cost on capture-heavy patterns. The interpreted runner pools
 * the same way via its {@code Scratch} ThreadLocal — this class is the
 * generated tier's equivalent, exposed as a {@code final} class so the
 * emitted {@code INVOKEVIRTUAL} is provably monomorphic (see
 * {@code EmittedBytecodePolicyTest}: every receiver in generated bytecode
 * must be final).
 *
 * <p>Correctness contract: callers must clone before a pooled array escapes
 * ({@code extractOne} clones into its result holder on success), and must
 * treat contents as undefined on take.
 */
@EmittedSurface  // incl. the default ctor: generated <init> emits INVOKESTATIC NEW/INVOKESPECIAL on it
public final class RegPool {

    private final ThreadLocal<int[]> slot = ThreadLocal.withInitial(() -> null);

    /**
     * Returns a pooled array of exactly {@code n} cells, contents undefined.
     * Grows (re-allocates) if the thread's cached array has a different
     * length — one pattern's engine per generated class, so resizes are
     * rare (first call, or shared pool across recompiles).
     */
    @EmittedSurface
    public int[] take(int n) {
        int[] r = slot.get();
        if (r == null || r.length != n) {
            r = new int[n];
            slot.set(r);
        }
        return r;
    }
}
